[[redirects]]
  from = "/home"
  to = "/index.html"
  status = 200

[[redirects]]
  from = "/products"
  to = "/products.html"
  status = 200

[[redirects]]
  from = "/more"
  to = "/more.html"
  status = 200

[[redirects]]
  from = "/legal"
  to = "/legal.html"
  status = 200
