[[redirects]]
  from = "/index.html"
  to = "/home"
  status = 301
  force = true

[[redirects]]
  from = "/products.html"
  to = "/products"
  status = 301
  force = true

[[redirects]]
  from = "/more.html"
  to = "/more"
  status = 301
  force = true

[[redirects]]
  from = "/legal.html"
  to = "/legal"
  status = 301
  force = true

[[headers]]
for = "/files/Building_Digital_Workflows.pdf"
[headers.values]
Content-Type = "application/pdf"

